import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const jobs = sqliteTable("jobs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  company: text("company").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  location: text("location"),
  workMode: text("work_mode").notNull(),
  employmentType: text("employment_type"),
  salaryText: text("salary_text"),
  salaryMin: real("salary_min"),
  salaryMax: real("salary_max"),
  salaryCurrency: text("salary_currency"),
  salaryNormalizedInrMin: real("salary_normalized_inr_min"),
  salaryNormalizedInrMax: real("salary_normalized_inr_max"),
  postedAt: integer("posted_at"),
  firstSeenAt: integer("first_seen_at").notNull(),
  lastSeenAt: integer("last_seen_at").notNull(),
  score: real("score"),
  deterministicScore: real("deterministic_score"),
  aiScore: real("ai_score"),
  applyUrl: text("apply_url").notNull(),
  jobUrl: text("job_url").notNull(),
  status: text("status").notNull().default("NEW"),
  isClosed: integer("is_closed").notNull().default(0),
  descriptionHash: text("description_hash").notNull(),
  profileVersion: integer("profile_version").notNull(),
  aiReason: text("ai_reason"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const jobSources = sqliteTable("job_sources", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  jobId: integer("job_id").notNull(),
  source: text("source").notNull(),
  sourceJobId: text("source_job_id"),
  jobUrl: text("job_url").notNull(),
  applyUrl: text("apply_url").notNull(),
  firstSeenAt: integer("first_seen_at").notNull(),
  lastSeenAt: integer("last_seen_at").notNull(),
});

export const jobScores = sqliteTable("job_scores", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  jobId: integer("job_id").notNull(),
  model: text("model").notNull(),
  profileVersion: integer("profile_version").notNull(),
  descriptionHash: text("description_hash").notNull(),
  score: real("score").notNull(),
  technicalMatch: real("technical_match").notNull(),
  experienceMatch: real("experience_match").notNull(),
  roleMatch: real("role_match").notNull(),
  locationMatch: real("location_match").notNull(),
  salaryMatch: real("salary_match").notNull(),
  matchedSkillsJson: text("matched_skills_json").notNull(),
  missingSkillsJson: text("missing_skills_json").notNull(),
  reason: text("reason").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const searchRuns = sqliteTable("search_runs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  startedAt: integer("started_at").notNull(),
  completedAt: integer("completed_at"),
  sourcesJson: text("sources_json").notNull(),
  filtersJson: text("filters_json").notNull(),
  jobsDiscovered: integer("jobs_discovered").notNull().default(0),
  jobsAfterFiltering: integer("jobs_after_filtering").notNull().default(0),
  duplicatesRemoved: integer("duplicates_removed").notNull().default(0),
  jobsAiScored: integer("jobs_ai_scored").notNull().default(0),
  jobsAboveThreshold: integer("jobs_above_threshold").notNull().default(0),
  newJobs: integer("new_jobs").notNull().default(0),
  errorsJson: text("errors_json").notNull().default("[]"),
  status: text("status").notNull().default("running"),
});
